version: '3.5'

services:
  app:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    image: mage-php
    container_name: mage-php
    volumes:
      - ./src:/var/www/app
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING_DEV}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK}
      - PHP_XDEBUG_REMOTE_PORT=${PHP_XDEBUG_REMOTE_PORT}

  cron:
    build:
      context: docker/cron
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    image: mage-cron
    container_name: mage-cron
    volumes:
      - ./src:/var/www/app
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING_DEV}
      - PHP_MAX_EXECUTION_TIME=${CRON_PHP_MAX_EXECUTION_TIME}
      - PHP_MEMORY_LIMIT=${CRON_PHP_MEMORY_LIMIT}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK}
      - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST}
      - PHP_XDEBUG_REMOTE_PORT=${PHP_XDEBUG_REMOTE_PORT}

  server:
    build: ./docker/nginx
    image: mage-server
    container_name: mage-server
    volumes:
      - ./src:/var/www/app
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mage-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_buffer_pool_size=${MYSQL_INNODB_BUFFER_POOL_SIZE}
      - --innodb_log_file_size=${MYSQL_INNODB_LOG_FILE_SIZE}
      - --innodb_log_buffer_size=${MYSQL_INNODB_LOG_BUFFER_SIZE}
      - --innodb_file_per_table=${MYSQL_INNODB_FILE_PER_TABLE}
      - --innodb_flush_method=${MYSQL_INNODB_FLUSH_METHOD}
      - --innodb_flush_log_at_trx_commit=${MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT}
      - --query_cache_size=${MYSQL_QUERY_CACHE_SIZE}
      - --max-allowed-packet=${MYSQL_MAX_ALLOWED_PACKET}
      - --max_connections=${MYSQL_MAX_CONNECTIONS}
      - --tmp_table_size=${MYSQL_TMP_TABLE_SIZE}
      - --max_heap_table_size=${MYSQL_MAX_HEAP_TABLE_SIZE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mage-db:/var/lib/mysql

volumes:
  mage-db: